### PR TITLE
Add a solution to "Too many file open" error

### PR DESCRIPTION
**Pull request by kacperlukawski**
Adding a solution to the "Error: Too many files open (OS error 24)". Suggested only Docker-related solution, as there seem to be various ways, and those might be googled easily.

### CODE REVIEW

**Review by timvisee — APPROVED** [review]
LGTM.

Is it worth it to also suggest what to do when not running Docker?
For example: `ulimit -n 10000` on Linux.

**Comment by kacperlukawski** [comment]
@timvisee Good idea! I wanted to avoid writing an article like https://woshub.com/too-many-open-files-error-linux/, but that's a pretty straightforward way

**Comment by timvisee** [comment]
Makes sense! Setting using `ulimit` is simple, but only sets it for that session. The article you linked shows a few good ways to make this limit persistent. But I guess the user can find that out themselves.

**Review by timvisee — APPROVED** [review]
:ok_hand:

**Pull request merged**
